# PR:
- name: 'ドキュメント更新'
  description: 'approvers/genkai-tax のドキュメント更新'
  color: '596aff'
- name: '会計報告更新'
  description: '会計報告更新'
  color: '59ff90'
- name: 'GitHub Actions'
  color: '906ee0'
- name: 'renovate'
  color: '66abad'

# Discussions:
- name: '質問: 未解決'
  description: '未解決の問題に付与するラベル'
  color: 'f6ff00'
- name: '質問: 解決済み'
  description: '解決済みの問題に付与するラベル'
  color: '00ff48'
- name: 'フィードバック'
  description: '限界税に関するフィードバック'
  color: '4287f5'
- name: 'ディスカッション'
  description: '限界税に関するディスカッション'
  color: 'f57842'
- name: '会計報告'
  description: '会計報告に対するディスカッション'
  color: 'e06e85'
- name: 'アナウンス'
  color: 'ff9cff'
